packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - esbuild
  - sharp

catalog:
  typescript: 5.8.2
  next: 16.0.10
  eslint-config-next: 16.0.10
  react: ^19.2.3
  react-dom: ^19.2.3
  eslint: ^9.0.0